Add try_borrow[_mut] and tests
bholley/atomic_refcell pull request #10
Opened 2020-10-06 20:42 UTC by sdleffler

Sorry, this is a rehash of #9 . This is my first time successfully using git rebase so please forgive my clumsiness. 😂 Seems to have done the trick though, looking at the diffs.

2020-10-07 23:22 UTC, bholley requested changes
Thanks for the patch! I have some architectural and soundness concerns which I think should be addressable with some careful work.

2020-10-07 23:22 UTC, bholley commented on src/lib.rs
> +    pub fn try_borrow(&self) -> Result<AtomicRef<T>, BorrowError> {
Let's put this directly after borrow() (so that the order is borrow, try_borrow, borrow_mut, try_borrow_mut).

Ideally we'd also implement borrow in terms of try_borrow.

2020-10-07 23:22 UTC, bholley commented on src/lib.rs
> +        // set back to zero.
This loses all the soundness considerations in that ::new() has, via do_panic(). I think we need to refactor do_panic so that it's usable in the try-scenario. Ideally then we'd drop AtomicBorrowRef::new() and only have AtomicBorrowRef::try_new(), which would be delegated to by AtomicRefCell::try_borrow(), which would be delegated to by AtomicRefCell::borrow(). Similar for the mut case.

2020-10-08 00:47 UTC, sdleffler commented on src/lib.rs
> +        // set back to zero.
Oh, yeah, I see what you mean. I'm guessing you're talking about the "too many immutable borrows" and too many panicked threads cases?

I think that maybe `do_panic` could be renamed to `do_sanity_check` or such, and then the final panic line removed, so that it only panics in the case of corrupted states. I'll mess with that and push an update.

2020-10-08 00:57 UTC, sdleffler commented on src/lib.rs
> +        // set back to zero.
Having pushed a new commit, I left `AtomicBorrowRefMut::try_new`/`AtomicBorrowRefMut::new` alone. I think they could be consolidated just like `AtomicBorrowRef::new` but there would need to be an error value indicating the error condition (already mutably borrowed vs. already immutably borrowed) which could be implemented as state held inside `BorrowMutError` and then we'd return `Result<AtomicBorrowRefMut, BorrowMutError>` from `AtomicBorrowRefMut::try_new`. Thoughts?

2021-03-13 15:18 UTC, jojolepro commented
Hello! I would like to know if it is possible to review and merge this pull request, and then publish atomic_refcell 0.2.0?
Thanks! :)

2021-03-19 23:06 UTC, merged

2021-03-19 23:07 UTC, bholley commented
Sorry this took me forever, I had trouble finding a quiet moment to page all the details back in. :-)

I have a few followup quibbles, but will implement them myself on top of the merged PR.

2021-03-20 00:39 UTC, bholley commented
Published as 0.1.7.

2021-03-20 15:45 UTC, jojolepro commented
this should probably be published as 0.2.0, as it is a breaking change and will break all crates depending on it upon running cargo update.

2021-03-20 16:43 UTC, bholley commented
This looks semantically compatible to me at first glance. Can you say more about the type of breakage you envision?