feat: support serde serialisation and deserialisation
bholley/atomic_refcell pull request #22
Opened 2023-08-09 08:02 UTC by aminya

2023-08-09 14:55 UTC, Imberflur commented on src/lib.rs
> +        T::serialize(&*self.borrow(), serializer)
For `RefCell`, `serde` uses `try_borrow`: <https://docs.rs/serde/1.0.183/src/serde/ser/impls.rs.html#593-606>

IMO, it would probably be useful to do that here too, so that the serialization returns an error rather than panicking if the value is already borrowed.

2023-08-09 21:18 UTC, aminya commented on src/lib.rs
> +        T::serialize(&*self.borrow(), serializer)
Fixed in [`ff93c42` (#22)](https://github.com/bholley/atomic_refcell/pull/22/commits/ff93c426f7be19d8484b012f79ab6d044bdd3ef2)

2023-08-14 19:00 UTC, bholley requested changes
Is there a reason to specify the patch level for these dependencies?

2023-08-14 19:05 UTC, aminya commented
> Is there a reason to specify the patch level for these dependencies?

That indicates that this package was tested with these dependencies. Cargo uses semver in its resolving phase.

2023-08-14 19:18 UTC, bholley commented
Absent any reason to believe this simple feature would break on serde 1.0, I would default to imposing as few restrictions as possible on the consumer. Please go ahead and change that (and serde_json too), lgtm otherwise.

2023-08-14 23:53 UTC, bholley commented
Thanks for the patch!

2023-08-14 23:53 UTC, merged